@startuml

    !includesub core.puml!common
    !includesub core.puml!Activity
    !includesub core.puml!Contribution
    !includesub core.puml!Contribution_to_Document
    !includesub core.puml!Contribution_to_Project
    !includesub core.puml!Contribution_to_Event
    !includesub core.puml!Involvement
    !includesub core.puml!Membership
    !includesub core.puml!Education
    !includesub core.puml!Employment
    !includesub core.puml!Affiliation_Statement
    !includesub core.puml!Contribution_Statement
    !includesub core.puml!Resource
    !includesub core.puml!Document
    !includesub core.puml!Project
    !includesub core.puml!Event
    !includesub core.puml!Agent
    !includesub core.puml!Group_or_Organisation_Unit

@enduml