@startuml

    !includesub core.puml!common
    !includesub core.puml!Agent
    !includesub core.puml!Person
    !includesub core.puml!OrgUnit
    !includesub core.puml!Group
    !includesub core.puml!OrgUnitWithMembers

@enduml