@startuml

    !includesub core.puml!common
    !includesub core.puml!Agent
    !includesub core.puml!Activity
    !includesub core.puml!Contribution
    !includesub core.puml!ContributionToDocument
    !includesub core.puml!AffiliationStatement
    !includesub core.puml!Document

@enduml