@startuml

    !includesub core.puml!common
    !includesub core.puml!Agent
    !includesub core.puml!Activity
    !includesub core.puml!Contribution
    !includesub core.puml!Contribution_to_Document
    !includesub core.puml!Contribution_Statement
    !includesub core.puml!Affiliation_Statement
    !includesub core.puml!Document
    !includesub core.puml!Resource
    !includesub core.puml!Document_isa_Resource
    !includesub core.puml!Funding
    !includesub core.puml!Resource_Usage_Statement

@enduml