@startuml
	!startsub common
	!define datatype(x) class x << (D,#FF7700) DataType>>
	hide empty members
	skinparam BoxPadding 120
	!endsub

    !startsub Contributorship
    class "Document"{
        title : Multilingual_String
        publicationDate : Date 
        doi : DOI
    }
    !endsub
    class "Textual_Document"{
    }
    class "Textual_Document_Accessibility_Specification"{
    }
    !startsub Agent
    class "Agent"{

    }
    class "Organisation_Unit"{
        name : Multilingual_String
        acronym : String
        address : Postal_Address
        rorId : ROR_Id
        webSiteURL : URL
        email : URL
    }
    class "Person"{
        name : Person_Name
        orcidId : ORCID_iD
    }
    datatype("Person_Name") {
        firstNames : Multilingual_String
        familyNames : Multilingual_String
        otherNames : Multilingual_String
    } 
    datatype("Postal_Address") {
        street : Multilingual_String 
        city : Multilingual_String
        zipCode : Multilingual_String 
        country : Country
    }
    class "Country"{
        name : Multilingual_String
        iso3166alphaCode : ISO3166_Alpha_Code
        iso3166NumericCode : ISO3166_Numeric_Code
        euCountryCode : EU_Country_Code
    }
	"Postal_Address" o--> "country" "Country"
    !endsub
    class "Authorship"{
        correspondingAuthorFlag : Boolean 
    }
    note left #yellow: author == contributor
    !startsub Contributorship
    class "Contributorship"{
        contacts : List<URI> 
        displayName : String
    }
    class "Contribution_Statement"{
    }
    class "Free_Text_Contribution_Statement"{
        statement : Multilingual_String
    }
    class "Affiliation_Statement"{
        displayAffiliation : String 
        address : Postal_Address
    }
    !endsub

!startsub Contributorship
"Affiliation_Statement" ..> "postalAddress" "Postal_Address"
"Affiliation_Statement" o-- "orgUnit" "Organisation_Unit"
"Affiliation_Statement" o-- "institution" "Organisation_Unit"
"Affiliation_Statement" o-- "Person"
"Contribution_Statement" <|-- "Free_Text_Contribution_Statement"
"Contributorship" "*" --r--* "Document"
"Contributorship" "*" --l--o "0..1 contributor" "Agent"
"Contributorship" o-- "affiliations *" "Affiliation_Statement"
"Contributorship" *-- "contributionStatements *" "Contribution_Statement"
!endsub
"Authorship" -r-* "Textual_Document"
"Contributorship" <|-u- "Authorship"
"Authorship" --o "0..1 author" "Agent"
!startsub Agent
"Person" ..> "name" "Person_Name"
"Agent" <|-- "Person"
"Agent" <|-- "Organisation_Unit"
"Organisation_Unit" ..> "address" "Postal_Address"
!endsub
"Document" <|-u- "Textual_Document"
"Textual_Document" *-r- "accessRights" "Textual_Document_Accessibility_Specification"
"Textual_Document" o---  "authors *" "Agent"
@enduml