@startuml
	object "<u>X:Person</u>" as X {
           personName = {
           \t firstNames = "Urlike"
           \t familyNames = "Reisach"
           } ^^ PersonName
           orcid_id = "https://orcid.org/0000-0003-3432-8728" ^^ ORCID_iD_Type
        }

    object "<u>Institution 1:OrgUnit</u>" as Ins1 {
    	    name = "Neu-Ulm University of Applied Sciences"@en,
    	    \t "Hochschule für angewandte Wissenschaften Neu-Ulm"@de
            acronym = "HNU"
            rorId = "https://ror.org/03ggzay52" ^^ ROR_ID_Type
            websiteURL = "https://www.hnu.de/en/" ^^ URI
    	}

    object "<u>Germany:Country</u>" as Ger {
           name = "Germany"@en, "Deutschland"@de
           iso3166alpha2Code = "DE" ^^ ISO_3166_Alpha2_Code
        }

    object "<u>Elsevier B.V.:OrgUnit</u>" as Elsevier {
            name = "Elsevier B.V."@en
        }

    object "<u>Affiliation 1 : AffiliationStatement</u>" as Aff1 {
            displayAffiliation = "Department of Information Management,
            \t Prof. Dr. Ulrike Reisach,
            \t Neu-Ulm University of Applied Sciences,
            \t Wiley-Street 1, D-89231 Neu-Ulm, Germany"
            postalAddress = {
            \t streetAddress = "Wiley-Street 1"
            \t city = "Neu-Ulm"
            \t country = Germany ^^ Country
            \t zipCode = "D-89231"
            } ^^ PostalAddress
            institution = Institution 1 ^^ OrgUnit
            person = X ^^ Person
        }

    object "<u>Authorship 1 : Authorship</u>" as Aut1 {
            contacts = [ "mailto:xxxxxxxx@hnu.de" ][Collection<URI>]
            displayName = "Ulrike Reisach"
            correspondingAuthorFlag = True
            author = X ^^ Agent
            document = 10.1016/j.ejor.2020.09.020 ^^ Document
            affiliations = [Affiliation 1] ^^ List<AffiliationStatement>
        }
    Aut1 o--> "author" X
    Aff1 o--> "institution" Ins1
    Aff1 o--> "country" Ger
    Aut1 *--> "0..* affiliations" Aff1

@enduml