@startuml

    !includesub core.puml!common
    !includesub core.puml!Agent
    !includesub core.puml!Activity
    !includesub core.puml!Membership
    !includesub core.puml!Person
    !includesub core.puml!Group
    !includesub core.puml!Organisation_Unit
    !includesub core.puml!Group_or_Organisation_Unit
    !includesub core.puml!Involvement
    !includesub core.puml!Affiliation_Statement

@enduml