@startuml

    !includesub core.puml!common
    !includesub core.puml!Agent
    !includesub core.puml!Activity
    !includesub core.puml!Membership
    !includesub core.puml!Person
    !includesub core.puml!Group
    !includesub core.puml!OrgUnit
    !includesub core.puml!OrgUnitWithMembers
    !includesub core.puml!AffiliationStatement

@enduml