name: attempt-server-connetion.yml
on:
  push:
    branches: autodeploy
jobs:
  connect:
    runs-on: ubuntu-latest
    name: connect
    steps:
      - name: connect ssh
        env:
          CERIF2_SERVER_KEY: ${{ secrets.CERIF2_SERVER_KEY }}
        run: |
          mkdir -p -m 700 .ssh
          umask 077
          echo $CERIF2_SERVER_KEY | base64 --decode > .ssh/id_ed25519
          echo 'cerif2.eu ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK1gSq5xdHG/Bvqk1kvevx18bSMnw1enaOTIdr7PEPdR' >.ssh/known_hosts
          ssh -v cerif2@cerif2.eu echo 'Hello, world!'
